title: Brook's Blog
description: Brook's Blog

url: https://BruceChen7.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Articles
   url: /articles
 - title: Categories
   url: /categories
 - title: About
   url: /about

social:
   github: BruceChen7
   # linkedin: in/yanan-zhao-7691317b?trk=hp-identity-photo
   # facebook: profile.php?id=100014334455077
   email: brucechen7@gmail.com

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

# google_analytics: "UA-89960542-1"

# development configurations
host: 0.0.0.0
